name: Build and Deploy to Server

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (test only)
        run: |
          docker build . \
            --build-arg OXYLABS_USERNAME=dummy \
            --build-arg OXYLABS_PASSWORD=dummy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            export OXYLABS_USERNAME='${{ secrets.OXYLABS_USERNAME }}'
            export OXYLABS_PASSWORD='${{ secrets.OXYLABS_PASSWORD }}'
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
